import Header from "./Header";
import "./globals.css";

export const metadata = {
  title: "Coming Soon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
